'use strict';
(()=>{
 const ORIGIN='https://tibia-command-74.calmstronglife.chatgpt.site',HOSTED=location.origin===ORIGIN||document.body.dataset.marketHost==='true',BASE=HOSTED?'':ORIGIN;
 const SERVERS=['Mythera','Miracle','DeusOLD','Exordion Aegis','Exordion Legacy','Exordion Bravora','Outro 7.4'];
 const CATS={equipamentos:'Equipamentos',runas:'Runas',suprimentos:'Suprimentos',outros:'Outros itens'};
 const catalogItems=()=>window.CATALOG?.items||[];
 const normalizeItem=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/\s+/g,' ');
 const itemForTitle=title=>catalogItems().find(item=>normalizeItem(item.name)===normalizeItem(title).replace(/^(vendo|compro)\s+/,'').replace(/\s+\(\d+\)$/, ''));
 const itemImage=item=>item?.image?(item.image.startsWith('assets/')?'https://tibiacommand74.github.io/'+item.image:item.image):null;
 const itemCategory=item=>item.category==='Runas'?'runas':['Comidas','Munições','Ferramentas'].includes(item.category)?'suprimentos':['Outros','Móveis','Quest'].includes(item.category)?'outros':'equipamentos';
 const STATUSES={pending:'Em análise',active:'Publicado',sold:'Vendido / concluído',rejected:'Não aprovado',deleted:'Removido'};
 const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const options=(values,current,empty='')=>(empty?`<option value="">${e(empty)}</option>`:'')+values.map(v=>`<option value="${e(v)}" ${v===current?'selected':''}>${e(CATS[v]||v)}</option>`).join('');
 const date=v=>new Date(v).toLocaleDateString('pt-BR');
 const moneyNote='A negociação acontece diretamente entre os jogadores. O Tibia Command não recebe pagamentos nem garante as negociações.';
 let generation=0;
 async function api(path,method='GET',data){const headers={};if(data!==undefined)headers['content-type']='application/json';const token=await window.CommunityAuth?.token();if(token)headers.authorization='Bearer '+token;const response=await fetch(BASE+'/api/market/'+path,{method,headers,credentials:HOSTED?'same-origin':'omit',body:data===undefined?undefined:JSON.stringify(data)});let result;try{result=await response.json();}catch{throw Error('Classificados temporariamente indisponíveis. Tente novamente.');}if(!response.ok||result.ok===false)throw Error(result.error||'Não foi possível concluir. Tente novamente.');return result;}
 const authButtons=`<button type="button" class="action" data-auth="signup">Criar conta</button><button type="button" class="action secondary" data-auth="login">Entrar</button>`;
 function contact(seller){if(seller.contactType==='instagram')return `<a class="action" href="https://www.instagram.com/${encodeURIComponent(seller.contact)}/" target="_blank" rel="noopener noreferrer">Falar no Instagram</a>`;if(seller.contactType==='whatsapp')return `<a class="action" href="https://wa.me/${encodeURIComponent(seller.contact)}" target="_blank" rel="noopener noreferrer">Falar no WhatsApp</a>`;return `<p class="market-game-contact">Contato no jogo: <strong>${e(seller.character)}</strong></p>`;}
 window.renderClassifieds=async el=>{
  const gen=++generation;let session=null,profile=null,moderator=false,tab='browse',page=0,rows=[],total=0,filters={q:'',server:'',category:'',kind:''};
  el.innerHTML=`<section class="market-hero"><div><p class="eyebrow">DE JOGADOR PARA JOGADOR</p><h1>Classificados <em>7.4</em></h1><p>Encontre itens no seu servidor e negocie diretamente com outros jogadores.</p></div><div id="market-account" class="market-account"><p>Carregando sua conta…</p></div></section><div class="market-tabs" role="group" aria-label="Área de classificados"><button type="button" data-market-tab="browse" class="active">Explorar anúncios</button><button type="button" data-market-tab="mine">Meus anúncios</button><button type="button" data-market-tab="profile">Meu perfil</button><button type="button" data-market-tab="moderation" hidden>Moderação</button></div><div id="market-body"></div><p class="market-disclaimer">${moneyNote} Anúncios de itens; personagens e contas ainda não estão disponíveis.</p><dialog id="market-dialog" aria-label="Detalhes do anúncio"><button type="button" class="market-close" aria-label="Fechar anúncio">×</button><div id="market-dialog-body"></div></dialog>`;
  const root=el,bodyEl=root.querySelector('#market-body'),account=root.querySelector('#market-account'),dialog=root.querySelector('#market-dialog'),dialogBody=root.querySelector('#market-dialog-body');
  dialog.querySelector('.market-close').onclick=()=>dialog.close();dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});
  const notice=(message,error=false)=>`<p class="market-message ${error?'error':''}" role="status">${e(message)}</p>`;
  function authBox(){account.innerHTML=session?`<strong>${e(profile?.alias||'Sua conta')}</strong><span>${e(session.email)}</span><div><button type="button" class="action" id="market-new">Criar anúncio</button><button type="button" id="community-signout" class="market-link">Sair</button></div>`:`<strong>Seu espaço na comunidade</strong><p>Entre para anunciar e administrar seus itens.</p>${authButtons}<small>O e-mail de acesso fica privado.</small>`;account.querySelector('#market-new')?.addEventListener('click',()=>{if(!profile)show('profile');else formListing();});root.querySelector('[data-market-tab="moderation"]').hidden=!moderator;bindAuth(account);account.querySelector('#community-signout')?.addEventListener('click',async()=>{await CommunityAuth.signOut();renderClassifieds(el);});}
  function requireAccount(){if(session)return true;bodyEl.innerHTML=`<div class="market-empty"><span class="market-symbol">♜</span><h2>Seu espaço de negociação</h2><p>Entre na conta para salvar seu contato e gerenciar seus anúncios.</p>${authButtons}<p class="filter-note">Os anúncios públicos podem ser consultados sem login.</p></div>`;bindAuth(bodyEl);return false;}
  function bindAuth(scope){scope.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>authForm(b.dataset.auth));}
  function signupThanks(email,signedIn=false){
   dialog.close();account.hidden=true;root.querySelector('.market-tabs').hidden=true;
   bodyEl.innerHTML=`<section class="market-signup-thanks" aria-labelledby="market-thanks-title" style="max-width:760px;margin:32px auto;padding:clamp(24px,5vw,56px);border:1px solid #8b713d;border-radius:20px;background:linear-gradient(145deg,#172630,#0d171e);text-align:center"><span aria-hidden="true" style="display:inline-grid;place-items:center;width:68px;height:68px;border:1px solid #bfa363;border-radius:50%;color:#edce88;font-size:32px;margin-bottom:20px">✓</span><p class="eyebrow">BEM-VINDO À COMUNIDADE</p><h2 id="market-thanks-title" tabindex="-1" style="font-size:clamp(26px,4vw,38px);line-height:1.2">Obrigado por se juntar ao Tibia Command!</h2><p style="line-height:1.7">${signedIn?'Sua conta está pronta. Agora você pode anunciar seus itens e conhecer outros jogadores.':'Falta só confirmar seu e-mail para começar a anunciar.'}</p>${signedIn?'':`<div style="padding:20px;margin:24px 0;border:1px solid #394c59;border-radius:12px;background:#0b151d;text-align:left"><h3 style="margin-top:0">Confira sua caixa de entrada</h3><p style="overflow-wrap:anywhere">Procure a confirmação em <strong>${e(email)}</strong> e clique no link recebido.</p><p class="filter-note">Não encontrou? Confira também a pasta de spam. Depois de confirmar, volte aqui e entre na sua conta.</p></div>`}<div class="market-card-actions" style="justify-content:center;flex-wrap:wrap;margin-top:24px"><button class="action" id="market-thanks-primary">${signedIn?'Criar meu primeiro anúncio':'Já confirmei — entrar'}</button><button class="action secondary" id="market-thanks-browse">Explorar anúncios</button></div><p class="filter-note" style="margin-top:24px">Seu contato será usado nos seus anúncios. O e-mail de acesso fica privado.</p></section>`;
   function restore(){account.hidden=false;root.querySelector('.market-tabs').hidden=false;}
   bodyEl.querySelector('#market-thanks-primary').onclick=()=>{restore();if(signedIn)formListing();else authForm('login');};
   bodyEl.querySelector('#market-thanks-browse').onclick=()=>{restore();show('browse');};
   const heading=bodyEl.querySelector('#market-thanks-title');heading.focus({preventScroll:true});heading.scrollIntoView({block:'center',behavior:'smooth'});
  }
  function authForm(mode='login'){
   const signup=mode==='signup',recover=mode==='recover',password=mode==='password';
   dialogBody.innerHTML=`<p class="eyebrow">COMUNIDADE TIBIA COMMAND 7.4</p><h2>${signup?'Criar minha conta':recover?'Recuperar senha':password?'Definir nova senha':'Entrar na minha conta'}</h2><p>${signup?'Cadastre seu contato uma vez. Ele aparecerá automaticamente nos seus anúncios.':'Sua conta da comunidade, com e-mail e senha.'}</p><form id="community-auth-form" class="market-form">${password?'':`<label>E-mail de acesso<input name="email" type="email" autocomplete="email" maxlength="254" required></label>`}${recover?'':`<label>${password?'Nova senha':'Senha'}<input name="password" type="password" autocomplete="${signup||password?'new-password':'current-password'}" minlength="10" maxlength="128" required></label>`}${signup||password?'<label>Confirmar senha<input name="confirm" type="password" autocomplete="new-password" minlength="10" maxlength="128" required></label>':''}${signup?`<label>Apelido público<input name="alias" minlength="2" maxlength="40" autocomplete="nickname" required></label><div class="market-form-pair"><label>Servidor principal<select name="server">${options(SERVERS,'Mythera')}</select></label><label>Personagem<input name="character" minlength="2" maxlength="40" required></label></div><label>Contato para negociação<select name="contactType"><option value="character">Pelo personagem no jogo</option><option value="instagram">Instagram</option><option value="whatsapp">WhatsApp</option></select></label><label id="community-contact-field" hidden>Contato público<input name="contact" maxlength="80"></label><p class="filter-note">Seu e-mail e senha ficam privados. O contato escolhido aparece nos seus anúncios.</p><label class="market-consent"><input type="checkbox" name="consent" required> Autorizo mostrar o contato escolhido nos meus anúncios.</label>`:''}<button type="submit" class="action">${signup?'Criar conta':recover?'Enviar link de recuperação':password?'Salvar nova senha':'Entrar'}</button><p id="community-auth-message" role="status"></p></form><div class="market-card-actions">${mode==='login'?'<button class="market-link" data-auth="signup">Ainda não tenho conta</button><button class="market-link" data-auth="recover">Esqueci minha senha</button>':mode==='password'?'':'<button class="market-link" data-auth="login">Já tenho conta — entrar</button>'}</div>`;
   if(!dialog.open)dialog.showModal();bindAuth(dialogBody);const form=dialogBody.querySelector('form'),message=form.querySelector('#community-auth-message');
   if(signup)form.elements.contactType.onchange=()=>{const type=form.elements.contactType.value;dialogBody.querySelector('#community-contact-field').hidden=type==='character';form.elements.contact.required=type!=='character';form.elements.contact.placeholder=type==='instagram'?'Usuário do Instagram':'Número com código do país e DDD';};
   form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('[type="submit"]');if((signup||password)&&form.elements.password.value!==form.elements.confirm.value){message.textContent='As senhas precisam ser iguais.';return;}button.disabled=true;message.textContent='Aguarde…';try{
    if(recover){await CommunityAuth.recover(form.elements.email.value.trim());message.textContent='Se esse e-mail estiver cadastrado, você receberá um link para recuperar a senha.';}
    else if(password){await CommunityAuth.changePassword(form.elements.password.value);dialog.close();renderClassifieds(el);}
    else if(signup){const p={alias:form.elements.alias.value.trim(),server:form.elements.server.value,character:form.elements.character.value.trim(),contactType:form.elements.contactType.value,contact:form.elements.contactType.value==='character'?form.elements.character.value.trim():form.elements.contact.value.trim(),publicContactConsent:form.elements.consent.checked};if(p.contactType==='instagram'&&!/^@?[A-Za-z0-9._]{1,30}$/.test(p.contact))throw Error('Informe somente o usuário do Instagram.');if(p.contactType==='whatsapp'&&!/^\d{10,15}$/.test(p.contact.replace(/[\s()+.-]/g,'')))throw Error('Informe WhatsApp com código do país e DDD.');const result=await CommunityAuth.signUp(form.elements.email.value.trim(),form.elements.password.value,p);form.elements.password.value='';form.elements.confirm.value='';if(result.signedIn){await api('profile','PUT',p);const current=await api('session');session=current.user;profile=current.profile;moderator=!!session?.moderator;authBox();}signupThanks(form.elements.email.value.trim(),result.signedIn);}
    else{await CommunityAuth.signIn(form.elements.email.value.trim(),form.elements.password.value);dialog.close();renderClassifieds(el);}
   }catch(error){message.textContent=error.message;}finally{button.disabled=false;}};
  }
  async function privateImages(scope){
   const images=[...scope.querySelectorAll('img[data-private-image]')];
   if(!images.length)return;
   try{const token=await CommunityAuth.token();if(!token)return;
    await Promise.all(images.map(async img=>{const response=await fetch(BASE+img.dataset.privateImage,{headers:{authorization:'Bearer '+token}});if(!response.ok||!img.isConnected)return;const url=URL.createObjectURL(await response.blob());if(!img.isConnected){URL.revokeObjectURL(url);return;}img.src=url;img.onload=img.onerror=()=>URL.revokeObjectURL(url);}));
   }catch{ /* Preserve the listing even when its preview is unavailable. */ }
  }
  function photo(row,cls=''){const catalogImage=itemImage(itemForTitle(row.title));if(catalogImage)return `<img ${cls?`class="${cls}"`:''} src="${e(catalogImage)}" alt="${e(row.title)}" loading="lazy" style="object-fit:contain;image-rendering:pixelated;padding:20px">`;const privatePhoto=row.status!=='active'||row.expiresAt<=new Date().toISOString();return `<img ${cls?`class="${cls}"`:''} ${privatePhoto?`data-private-image="${e(row.image)}"`:`src="${e(BASE+row.image)}"`} alt="Foto de ${e(row.title)}" loading="lazy">`;}
  function card(row,own=false){const expired=row.expiresAt<=new Date().toISOString();return `<article class="market-card"><div class="market-card-art">${(row.image||itemImage(itemForTitle(row.title)))?photo(row):`<span aria-hidden="true">${row.category==='runas'?'✦':row.category==='equipamentos'?'⚔':'◈'}</span>`}<span class="market-kind">${row.kind==='buy'?'COMPRO':'VENDO'}</span></div><div class="market-card-content"><div class="market-card-meta"><span>${e(row.server)}</span><span>${e(CATS[row.category])}</span></div><h3>${e(row.title)}</h3><strong class="market-price">${e(row.price)}</strong><p>Quantidade: <strong>${e(row.quantity??1)}</strong></p>${row.description?`<p>${e(row.description)}</p>`:''}<div class="market-seller">${e(row.seller.alias)} · ${e(row.seller.character)}</div>${own?`<span class="market-status ${e(row.status)}">${expired?'Expirado':e(STATUSES[row.status]||row.status)}</span>${row.moderationReason?`<p class="market-reason">${e(row.moderationReason)}</p>`:''}<div class="market-card-actions"><button class="action secondary" data-market-edit="${row.id}">Editar</button>${['active','pending'].includes(row.status)?`<button class="market-link" data-market-sold="${row.id}">${row.kind==='buy'?'Concluído':'Vendido'}</button>`:''}<button class="market-link" data-market-remove="${row.id}">Remover</button></div>`:`<button class="action secondary" data-market-view="${row.id}">Ver anúncio e contato</button>`}</div></article>`;}
  async function changeStatus(row,status){dialogBody.innerHTML=`<h2>${status==='deleted'?'Remover anúncio?':'Concluir anúncio?'}</h2><p>${e(row.title)} sairá dos anúncios públicos.</p><button class="action" id="market-confirm">Confirmar</button> <button class="action secondary" id="market-dismiss">Cancelar</button><div id="market-action-message"></div>`;dialog.showModal();dialogBody.querySelector('#market-dismiss').onclick=()=>dialog.close();dialogBody.querySelector('#market-confirm').onclick=async event=>{event.target.disabled=true;try{await api('listings/'+row.id+'/status','POST',{status});dialog.close();await listings();}catch(error){dialogBody.querySelector('#market-action-message').innerHTML=notice(error.message,true);event.target.disabled=false;}};}
  function detail(row){dialogBody.innerHTML=`<p class="eyebrow">${e(row.server)} · ${row.kind==='buy'?'COMPRO':'VENDO'}</p><h2>${e(row.title)}</h2>${(row.image||itemImage(itemForTitle(row.title)))?photo(row,'market-detail-image'):''}<strong class="market-price">${e(row.price)}</strong><p>Quantidade: <strong>${e(row.quantity??1)}</strong></p>${row.description?`<p class="market-description">${e(row.description)}</p>`:''}<section class="market-contact"><h3>Anunciante: ${e(row.seller.alias)}</h3><p>Personagem: ${e(row.seller.character)}</p><small>Na comunidade desde ${date(row.seller.joinedAt)}</small>${contact(row.seller)}</section><p class="filter-note">Publicado em ${date(row.createdAt)} · Válido até ${date(row.expiresAt)}</p><p class="market-disclaimer">${moneyNote} Confira as regras do servidor e nunca compartilhe sua senha.</p><button class="market-link" id="market-report">Denunciar anúncio</button><div id="market-report-box"></div>`;dialog.showModal();privateImages(dialogBody);dialogBody.querySelector('#market-report').onclick=()=>{const box=dialogBody.querySelector('#market-report-box');if(!session){box.innerHTML=`<p>Entre na sua conta para enviar uma denúncia.</p>${authButtons}`;bindAuth(box);return;}box.innerHTML=`<form id="market-report-form"><label>Por que deseja denunciar?<textarea name="reason" minlength="10" maxlength="500" required rows="3"></textarea></label><button class="action">Enviar denúncia</button><div role="status"></div></form>`;box.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.target,button=form.querySelector('button');button.disabled=true;try{await api('listings/'+row.id+'/report','POST',{reason:form.elements.reason.value});box.innerHTML=notice('Denúncia recebida. A moderação vai revisar.');}catch(error){form.querySelector('[role="status"]').textContent=error.message;button.disabled=false;}};};}
  function bindCards(own=false){privateImages(bodyEl);bodyEl.querySelectorAll('[data-market-view]').forEach(b=>b.onclick=()=>detail(rows.find(r=>r.id===b.dataset.marketView)));bodyEl.querySelectorAll('[data-market-edit]').forEach(b=>b.onclick=()=>formListing(rows.find(r=>r.id===b.dataset.marketEdit)));bodyEl.querySelectorAll('[data-market-sold]').forEach(b=>b.onclick=()=>changeStatus(rows.find(r=>r.id===b.dataset.marketSold),'sold'));bodyEl.querySelectorAll('[data-market-remove]').forEach(b=>b.onclick=()=>changeStatus(rows.find(r=>r.id===b.dataset.marketRemove),'deleted'));}
  async function listings(){const requestGen=++generation;const mine=tab==='mine';if(mine&&!requireAccount())return;
   bodyEl.innerHTML=(mine?`<div class="market-section-head"><div><h2>Meus anúncios</h2><p>Gerencie seus anúncios e marque as negociações concluídas.</p></div><button class="action" id="market-add">Criar anúncio</button></div>`:`<form class="market-filters" id="market-search"><label>Buscar item<input name="q" value="${e(filters.q)}" maxlength="80" placeholder="Ex.: plate armor, rope, runas…"></label><label>Servidor<select name="server">${options(SERVERS,filters.server,'Todos os servidores')}</select></label><label hidden>Categoria<select name="category">${options(Object.keys(CATS),filters.category,'Todos os itens')}</select></label><label>Negociação<select name="kind"><option value="">Compra e venda</option><option value="sell" ${filters.kind==='sell'?'selected':''}>Vendo</option><option value="buy" ${filters.kind==='buy'?'selected':''}>Compro</option></select></label><button class="action">Buscar</button></form>`)+`<div id="market-results" aria-live="polite">${notice('Carregando anúncios…')}</div>`;
   bodyEl.querySelector('#market-add')?.addEventListener('click',()=>profile?formListing():show('profile'));
   bodyEl.querySelector('#market-search')?.addEventListener('submit',event=>{event.preventDefault();filters=Object.fromEntries(new FormData(event.target));page=0;listings();});
   try{const query=new URLSearchParams({...filters,page:String(page),...(mine?{mine:'1'}:{})});const result=await api('listings?'+query);if(requestGen!==generation||!root.isConnected)return;rows=result.listings;total=result.total;
    const results=bodyEl.querySelector('#market-results');results.innerHTML=`<p class="market-result-count">${total} ${total===1?'anúncio':'anúncios'}${mine?' na sua conta':''}</p>`+(rows.length?`<div class="market-grid">${rows.map(r=>card(r,mine)).join('')}</div>`:`<div class="market-empty"><span class="market-symbol">⚔</span><h2>${mine?'Seu primeiro anúncio começa aqui':filters.q||filters.server||filters.category||filters.kind?'Nenhum anúncio encontrado':'A feira está abrindo as portas'}</h2><p>${mine?'Complete seu perfil e anuncie um item.':'Seja um dos primeiros a anunciar. Os anúncios aparecem aqui depois da aprovação.'}</p>${mine?'<button class="action" id="market-first">Criar anúncio</button>':`<button class="action" id="market-first">Quero anunciar</button>`}</div>`)+`<div class="market-pagination"><button class="action secondary" id="market-prev" ${page===0?'disabled':''}>Anterior</button><span>Página ${page+1} de ${Math.max(1,Math.ceil(total/24))}</span><button class="action secondary" id="market-next" ${(page+1)*24>=total?'disabled':''}>Próxima</button></div>`;
    bindCards(mine);results.querySelector('#market-first')?.addEventListener('click',()=>session?(profile?formListing():show('profile')):show('mine'));results.querySelector('#market-prev').onclick=()=>{page--;listings();};results.querySelector('#market-next').onclick=()=>{page++;listings();};
   }catch(error){if(requestGen!==generation)return;bodyEl.querySelector('#market-results').innerHTML=notice(error.message,true)+'<button class="action secondary" id="market-retry">Tentar novamente</button>';bodyEl.querySelector('#market-retry').onclick=listings;}
  }
  function profileForm(){if(!requireAccount())return;const p=profile||{alias:'',character:'',server:'Mythera',contactType:'character',contact:''};bodyEl.innerHTML=`<div class="market-form-shell"><div><p class="eyebrow">SEU CONTATO, DO SEU JEITO</p><h2>Meu perfil</h2><p>Seu contato será usado automaticamente nos anúncios. Alterações aqui atualizam todos eles.</p><p class="market-disclaimer">O e-mail de acesso fica privado. Apelido, personagem e contato escolhido ficam públicos quando você tem um anúncio aprovado.</p></div><form id="market-profile-form" class="market-form"><label>Apelido público<input name="alias" minlength="2" maxlength="40" value="${e(p.alias)}" required autocomplete="nickname"></label><div class="market-form-pair"><label>Servidor principal<select name="server">${options(SERVERS,p.server)}</select></label><label>Personagem de contato<input name="character" minlength="2" maxlength="40" value="${e(p.character)}" placeholder="Nome no jogo" required></label></div><label>Como o comprador fala com você?<select name="contactType"><option value="character" ${p.contactType==='character'?'selected':''}>Pelo personagem no jogo</option><option value="instagram" ${p.contactType==='instagram'?'selected':''}>Instagram</option><option value="whatsapp" ${p.contactType==='whatsapp'?'selected':''}>WhatsApp</option></select></label><label id="market-contact-field">Contato público<input name="contact" maxlength="80" value="${e(p.contact)}"></label><p class="filter-note" id="market-contact-help"></p><label class="market-consent"><input type="checkbox" name="consent" required> Autorizo mostrar esse contato publicamente nos meus anúncios.</label><button class="action" type="submit">Salvar perfil</button><div id="market-profile-message" role="status"></div></form></div>`;
   const form=bodyEl.querySelector('form');function contactField(){const type=form.elements.contactType.value;bodyEl.querySelector('#market-contact-field').hidden=type==='character';form.elements.contact.required=type!=='character';form.elements.contact.placeholder=type==='instagram'?'Seu usuário, sem o link':'Ex.: 5551999999999';bodyEl.querySelector('#market-contact-help').textContent=type==='character'?'O nome do personagem será o contato público.':type==='whatsapp'?'Seu número ficará público. Inclua código do país e DDD.':'Informe seu usuário do Instagram.';}form.elements.contactType.onchange=contactField;contactField();
   form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button'),message=bodyEl.querySelector('#market-profile-message');button.disabled=true;try{const result=await api('profile','PUT',{alias:form.elements.alias.value,server:form.elements.server.value,character:form.elements.character.value,contactType:form.elements.contactType.value,contact:form.elements.contactType.value==='character'?form.elements.character.value:form.elements.contact.value,publicContactConsent:form.elements.consent.checked});profile=result.profile;authBox();message.textContent='Perfil salvo. Seu contato já está pronto para os anúncios.';}catch(error){message.textContent=error.message;}finally{button.disabled=false;}};
  }
  function formListing(row){if(!requireAccount())return;if(!profile){show('profile');return;}const v=row||{title:'',description:'',server:profile.server,category:'equipamentos',kind:'sell',price:'',quantity:1};let id=row?.id||crypto.randomUUID(),saved=false;
   bodyEl.innerHTML=`<div class="market-form-shell"><div><p class="eyebrow">SUA PRÓXIMA NEGOCIAÇÃO</p><h2>${row?'Editar anúncio':'Novo anúncio'}</h2><p>Escolha o item, informe a quantidade e o preço. Seu contato já está preenchido.</p><div class="market-contact"><strong>${e(profile.alias)}</strong><p>${e(profile.character)} · ${e(profile.server)}</p><p>${profile.contactType==='character'?'Contato no jogo':profile.contactType==='instagram'?'Instagram':'WhatsApp'}: ${e(profile.contact)}</p><button class="market-link" id="market-change-profile">Alterar contato</button></div><p class="market-disclaimer">Seu anúncio aparece assim que você publicar. Validade de 30 dias; edite para renovar.</p></div><form id="market-listing-form" class="market-form"><div class="market-form-pair"><label>Tipo<select name="kind"><option value="sell" ${v.kind==='sell'?'selected':''}>Vendo</option><option value="buy" ${v.kind==='buy'?'selected':''}>Compro</option></select></label><label>Servidor<select name="server">${options(SERVERS,v.server)}</select></label></div><label>Buscar item da biblioteca<input name="title" list="market-catalog-items" autocomplete="off" minlength="3" maxlength="80" value="${e(itemForTitle(v.title)?.name||v.title)}" placeholder="Digite o nome, ex.: plate armor" aria-describedby="market-item-help" required></label><datalist id="market-catalog-items">${catalogItems().filter(item=>itemImage(item)).sort((a,b)=>a.name.localeCompare(b.name)).map(item=>`<option value="${e(item.name)}">${e(item.category)}</option>`).join('')}</datalist><div id="market-selected-item" class="market-contact" aria-live="polite"></div><p id="market-item-help" class="filter-note">Escolha um item nas sugestões. A imagem vem automaticamente da nossa biblioteca.</p><div><label hidden>Categoria<select name="category">${options(Object.keys(CATS),v.category)}</select></label><div class="market-form-pair"><label>Quantidade<input name="quantity" type="number" min="1" max="999999" step="1" value="${e(v.quantity??1)}" required></label><label>Preço ou proposta<input name="price" maxlength="60" value="${e(v.price)}" placeholder="Ex.: 1.500 gold ou a combinar" required></label></div></div><label>Descrição (opcional)<textarea name="description" maxlength="1500" rows="3" placeholder="Detalhes ou condições da negociação…">${e(v.description)}</textarea></label><div class="market-card-actions"><button class="action" type="submit">${row?'Salvar alterações':'Publicar anúncio'}</button><button class="action secondary" type="button" id="market-cancel-form">Voltar</button></div><div id="market-save-message" role="status"></div></form></div>`;
   bodyEl.querySelector('#market-change-profile').onclick=()=>show('profile');bodyEl.querySelector('#market-cancel-form').onclick=()=>show('mine');const form=bodyEl.querySelector('form');
   function previewItem(){const item=itemForTitle(form.elements.title.value),box=bodyEl.querySelector('#market-selected-item');if(item&&itemImage(item)){box.innerHTML=`<div style="display:flex;align-items:center;gap:18px"><img src="${e(itemImage(item))}" width="64" height="64" alt="${e(item.name)}" style="object-fit:contain;image-rendering:pixelated"><div><strong>${e(item.name)}</strong><p style="margin:6px 0 0">${e(item.category)} · Imagem automática</p></div></div>`;form.elements.category.value=itemCategory(item);form.elements.title.setCustomValidity('');}else{box.textContent='Digite o nome e selecione o item que deseja anunciar.';form.elements.title.setCustomValidity('Escolha um item da biblioteca nas sugestões.');}}
   form.elements.title.oninput=previewItem;form.elements.title.onchange=previewItem;previewItem();
   form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('[type="submit"]'),message=bodyEl.querySelector('#market-save-message'),item=itemForTitle(form.elements.title.value);if(!item||!itemImage(item)){message.textContent='Escolha um item da biblioteca nas sugestões.';return;}button.disabled=true;try{const data={id,title:item.name,description:form.elements.description.value,quantity:Number(form.elements.quantity.value),server:form.elements.server.value,category:form.elements.category.value,kind:form.elements.kind.value,price:form.elements.price.value};await api(row||saved?'listings/'+id:'listings',row||saved?'PUT':'POST',data);saved=true;show('mine');}catch(error){message.textContent=error.message;button.disabled=false;}};
  }
  async function moderation(){if(!moderator||!requireAccount())return;bodyEl.innerHTML=notice('Carregando fila de análise…');try{const result=await api('moderation');bodyEl.innerHTML=`<div class="market-section-head"><div><h2>Moderação</h2><p>Revise os anúncios antes de publicar.</p></div><button class="action secondary" id="market-refresh">Atualizar</button></div><h3>Anúncios em análise (${result.listings.length})</h3><div class="market-grid">${result.listings.map(row=>`<div>${card(row)}<div class="market-moderator-actions"><button class="action" data-approve="${row.id}">Aprovar</button><button class="action secondary" data-reject="${row.id}">Recusar</button></div></div>`).join('')||'<p>Nenhum anúncio aguardando análise.</p>'}</div><h3>Denúncias (${result.reports.length})</h3>${result.reports.map(r=>`<article class="market-report-row"><h4>${e(r.title)}</h4><p>${e(r.reason)}</p><button class="action secondary" data-reject="${r.listing_id}">Retirar anúncio</button></article>`).join('')||'<p>Nenhuma denúncia aberta.</p>'}<div id="market-mod-message" role="status"></div>`;rows=result.listings;bindCards();bodyEl.querySelector('#market-refresh').onclick=moderation;
    async function moderate(id,status,reason=''){await api('moderation','POST',{id,status,reason});await moderation();}
    bodyEl.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await moderate(b.dataset.approve,'active');}catch(error){bodyEl.querySelector('#market-mod-message').textContent=error.message;b.disabled=false;}});
    bodyEl.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>{dialogBody.innerHTML='<h2>Motivo da recusa</h2><form id="market-reject-form"><label>Informe o que precisa ser corrigido<textarea name="reason" required minlength="3" maxlength="300" rows="3"></textarea></label><button class="action">Confirmar recusa</button><p role="status"></p></form>';dialog.showModal();dialogBody.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.target;form.querySelector('button').disabled=true;try{await moderate(b.dataset.reject,'rejected',form.elements.reason.value);dialog.close();}catch(error){form.querySelector('[role="status"]').textContent=error.message;form.querySelector('button').disabled=false;}};});
   }catch(error){bodyEl.innerHTML=notice(error.message,true);}}
  function show(next){generation++;tab=next;page=0;root.querySelectorAll('[data-market-tab]').forEach(b=>b.classList.toggle('active',b.dataset.marketTab===tab));if(next==='profile')profileForm();else if(next==='moderation')moderation();else listings();}
  root.querySelectorAll('[data-market-tab]').forEach(b=>b.onclick=()=>show(b.dataset.marketTab));
  try{{const result=await api('session');if(gen!==generation||!root.isConnected)return;session=result.user;profile=result.profile;moderator=!!session?.moderator;}authBox();show('browse');if(CommunityAuth.isRecovery())authForm('password');}catch(error){account.innerHTML=notice(error.message,true);show('browse');}
 };
})();
