const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map(),ctx=new Proxy({},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});function node(id){if(!nodes.has(id))nodes.set(id,{value:'',hidden:false,checked:false,innerHTML:'',textContent:'',parentElement:{clientWidth:800,clientHeight:600},querySelectorAll:()=>[],close(){},showModal(){},addEventListener(){},getContext:()=>ctx});return nodes.get(id);}
const env={window:{},document:{querySelector:node,querySelectorAll:()=>[]},localStorage:{getItem:()=>null,setItem(){}},Image:class{complete=false},ResizeObserver:class{observe(){}disconnect(){}},location:{hash:''},URL,console,setTimeout,clearTimeout};vm.createContext(env);
for(const f of ['data.js','catalog-data.js','catalog.js','adventures.js','quest-catalog.js','quest-route-data.js','quest-map-guides.js','route-review.js','reports.js','quest-routes.js','hunt-data.js','hunt-paths.js','hunts.js'])vm.runInContext(fs.readFileSync('public/'+f,'utf8'),env);vm.runInContext(fs.readFileSync('public/app.js','utf8').split("\ndocument.querySelectorAll('nav button[data-page]')")[0],env);const run=s=>vm.runInContext(s,env);
assert.equal(env.window.CLASSIC_HUNTS.length,14);assert.equal(new Set(env.window.CLASSIC_HUNTS.map(h=>h.id)).size,14);
let segments=0;for(const h of env.window.CLASSIC_HUNTS){assert(run(`Boolean(huntCreature(${JSON.stringify(h)}))`));assert(h.sources.every(s=>new URL(s).protocol==='https:'));assert(h.preparation.length>=3&&h.rotation.length>=3);assert(env.window.DATA.map.spawns.some(s=>s[0].toLowerCase()===h.mob&&s.slice(1,4).join()===h.xyz.join()),'Pin must be an actual respawn in the local base');const r=env.window.HUNT_PATHS[h.id];assert.equal(r.floor,h.xyz[2]);for(const path of r.segments){segments++;assert(path.length>=2);for(const p of path)assert.equal(p[2],r.floor);for(let i=1;i<path.length;i++)assert(path[i][0]===path[i-1][0]||path[i][1]===path[i-1][1]);}run(`detailHunt(${JSON.stringify(h.id)})`);assert(node('#detail-body').innerHTML.includes(h.name));assert(node('#detail-body').innerHTML.includes('onde vender'));assert(node('#detail-body').innerHTML.includes('Ausência de imunidade não indica fraqueza'));run(`openHuntMap(${JSON.stringify(h.id)});bindMap()`);assert.equal(run('activeHuntMap'),h.id);assert.equal(run('activeQuestRoute'),null);assert.equal(run('mapState.z'),h.xyz[2]);assert.equal(node('#hunt-map-guide').hidden,false);assert(Number.isFinite(run('mapState.x')));}
assert(segments>=20);run('renderHunts(document.querySelector("#content"))');assert.equal((node('#hunt-grid').innerHTML.match(/data-hunt-guide=/g)||[]).length,14);
run("huntQuery='amazon';paintHunts()");assert.equal(run('huntRows().length'),1);run("huntQuery='';huntCity='Ankrahmun';paintHunts()");assert.equal(run('huntRows().length'),3);run("huntCity='';huntAccess='free';paintHunts()");assert(run('huntRows().every(h=>!h.premium)'));run("huntAccess='';huntVocation='Knight';huntLevel='20';paintHunts()");assert(run('huntRows().every(h=>h.level<=20&&h.vocations.includes("Knight"))'));node('#hunt-clear').onclick();assert.equal(run('huntRows().length'),14);
run("openHuntMap('ancient-scarab');bindMap()");node('#floor').value='7';node('#floor').onchange({target:node('#floor')});assert.equal(node('#hunt-map-floor').hidden,false);
run("openQuestRoute('fibula');bindMap()");assert.equal(run('activeHuntMap'),null);assert.equal(node('#hunt-map-guide').hidden,true);assert.equal(run('activeQuestRoute'),'fibula');run("openHuntMap('amazon-venore');bindMap()");node('#map-reset').onclick();assert.equal(run('activeHuntMap'),null);assert.equal(run('activeQuestRoute'),null);
assert(!node('#content').innerHTML.includes('Personagem<select'));assert(!fs.readFileSync('public/hunts.js','utf8').includes('localStorage'));
console.log(`PASS: 14 guias, ${segments} trechos por andar, respawns reais da base, filtros combinados, loot, imunidades, mapa, transições e ausência de cadastro pessoal`);
