'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map();function node(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',hidden:false,open:false,querySelectorAll:()=>[],querySelector:()=>null,showModal(){this.open=true;},close(){this.open=false;}});return nodes.get(id);}
const env={window:{},console,document:{querySelectorAll:()=>[]},$:node,esc:s=>String(s??''),fmt:n=>String(n),options:(a,v,label)=>`<option>${label}</option>`+a.map(x=>`<option>${x}</option>`).join(''),title:(a,b)=>`<h2>${a}</h2><p>${b}</p>`,reportButton:()=>'',bindContextReports:()=>{}};vm.createContext(env);
for(const f of ['catalog-data.js','catalog.js'])vm.runInContext(fs.readFileSync(f,'utf8'),env);const run=s=>vm.runInContext(s,env),d=env.window.CATALOG;
assert.equal(d.services.length,5);assert(!d.items.some(i=>['antidote','sudden death','promotion','folda','senja','vega','sqare pillow','arrows',"devil's helmet"].includes(i.name)));
const duria=d.npcs.find(n=>n.name==='Duria');assert.equal(duria.sell.length,0);assert(duria.spellOffers.some(s=>s.name==='Antidote'&&s.price===150));
const nielson=d.npcs.find(n=>n.name==='Nielson');assert.equal(nielson.sell.length,0);assert.equal(nielson.services.length,3);assert(nielson.services.every(s=>s.price===20));
const helmet=d.items.find(i=>i.id===2462);assert(helmet.sell.some(o=>o.npc==='Kroox'&&o.price===450));assert.equal(d.itemAliases['ref-devilshelmet'],2462);
run(`catalogQuery=${JSON.stringify("devil's helmet")};catalogTab='itens'`);assert.equal(run('catalogRows().length'),1);
run("catalogQuery='';catalogTab='servicos';renderCatalog($('content'))");assert(node('#catalog-grid').innerHTML.includes('Passagem para Folda'));assert(node('content').innerHTML.includes('Tipo de serviço'));
run("catalogQuery='Nielson'");assert.equal(run('catalogRows().length'),3);
run("catalogQuery='';catalogCategory='Promoção'");assert.equal(run('catalogRows().length'),1);
run("detailService('ref-folda')");assert(node('#detail-body').innerHTML.includes('Nielson'));assert(node('#detail-body').innerHTML.includes('20 gp'));
run("detailNpc('Nielson')");assert(node('#detail-body').innerHTML.includes('Serviços disponíveis'));assert(!node('#detail-body').innerHTML.includes('data-catalog-item="ref-folda"'));
run("catalogVocation='';detailSpell('Antidote')");assert(node('#detail-body').innerHTML.includes('Preços registrados por NPC'));assert(node('#detail-body').innerHTML.includes('Duria'));
for(const s of d.spells.filter(s=>s.runeId&&d.items.some(i=>i.id===s.runeId)))assert.equal(s.image,d.items.find(i=>i.id===s.runeId)?.image);
for(const [id,target]of Object.entries(d.itemAliases))assert(d.items.some(i=>String(i.id)===String(target)),id);
for(const f of ['catalog.js','catalog-data.js','index.html'])assert.equal(fs.readFileSync(f,'utf8'),fs.readFileSync('public/'+f,'utf8'));
console.log('PASS: separação de magias/serviços, preços preservados, aliases, links legados, filtros e imagens de runas');
